# Recommender Network for Movies
by Alexander Köhn

## Information for the tester
In the following my whole Software contribution is shown via a Jupyter notebook. My Final Report is included during the Notebook at the relevant parts of my code.
The summary of the tutorials are in an extra file in my repository.

## Credits
I got information for this project from the Tutorial (https://keras.io/examples/structured_data/collaborative_filtering_movielens/) and (https://www.tensorflow.org/recommenders/examples/basic_retrieval)

## Project Goal and underlying topic
The Project Goal is to implement a recommender system for love pairs, which want to watch a movie together during the winter holidays. The motivation is to reduce the time couples spend searching for the right movie.
Common Platforms use recommender systems with the data of the signed account. These Systems are not achieving the best results, if the account is most often used alone by one person and just used sometimes to watch movies together.
Implementing a recommender system with the input of two people, which want to watch a movie together, and a output of movies, which are good for both of them, is the Goal.

Additionally we want to have some more features.
1. We can decide which users interest is more important for the network.
2. We can decide if the network should recommend a movie they will likely watch (Retrieval) or they will likely like (Ranking)

## Inputs
First we need some Packages for building the network and analysing the data.

In [ ]:
%pip install -q tensorflow-recommenders
%pip install -q --upgrade tensorflow-datasets
%pip install -q scann

In [ ]:
import os
import pprint
import tempfile

from typing import Dict, Text

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

import pandas as pd

## Data
We are using the Movielens 100K Dataset, which features a set with 100,000 ratings (1-5) from 943 users on 1682 movies. Tensorflow already provides a method to download the Dataset to the hard disk. After the first download the dataset from the disk will be used.

In [17]:
# Ratings data.
ratings = tfds.load("movielens/100k-ratings", split="train")
# Features of all the available movies.
movies = tfds.load("movielens/100k-movies", split="train")

As you can see, each rating consists of a movie with specific genres and a user with demographic information.

In [18]:
for x in ratings.take(1).as_numpy_iterator():
  pprint.pprint(x)

{'bucketized_user_age': 45.0,
 'movie_genres': array([7], dtype=int64),
 'movie_id': b'357',
 'movie_title': b"One Flew Over the Cuckoo's Nest (1975)",
 'raw_user_age': 46.0,
 'timestamp': 879024327,
 'user_gender': True,
 'user_id': b'138',
 'user_occupation_label': 4,
 'user_occupation_text': b'doctor',
 'user_rating': 4.0,
 'user_zip_code': b'53211'}


In [19]:
for x in movies.take(1).as_numpy_iterator():
  pprint.pprint(x)

{'movie_genres': array([4], dtype=int64),
 'movie_id': b'1681',
 'movie_title': b'You So Crazy (1994)'}


## Analaysis of the data
We can gain a better intuition for the dataset if we gather information about statistical information of the dataset.


## Prepocessing of the data


To simplify our model we will only use the user_id, movie_title and the user_rating from the Dataset.

In [20]:
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
    "user_rating": x["user_rating"],
})
movies = movies.map(lambda x: x["movie_title"])

We are shuffling the data of the rating to randomize the learning and to avoid a bias in the train and test data.

In [21]:
tf.random.set_seed(37)
shuffled = ratings.shuffle(100_000, seed=37, reshuffle_each_iteration=False)

We are dividing the dataset in 80 % train data and 20% test data.

In [22]:
train = shuffled.take(80_000)
test = shuffled.skip(80_000).take(20_000)

Now we want to get two lists. The first list unique_movie_titles consists of all the movie titles, but every title is only saved once in the list. The second list unique_user_ids consists of all the users, in the same was as the first.

In [23]:
movie_titles = movies.batch(1_000)
user_ids = ratings.batch(1_000_000).map(lambda y: y["user_id"])

unique_movie_titles = np.unique(np.concatenate(list(movie_titles)))
unique_user_ids = np.unique(np.concatenate(list(user_ids)))

print("First 10 Movie titles: ")
print(unique_movie_titles[:10])

print("\nThe total count of users: ", len(unique_user_ids))
print("The total count of movies: ", len(unique_movie_titles))

First 10 Movie titles: 
[b"'Til There Was You (1997)" b'1-900 (1994)' b'101 Dalmatians (1996)'
 b'12 Angry Men (1957)' b'187 (1997)' b'2 Days in the Valley (1996)'
 b'20,000 Leagues Under the Sea (1954)' b'2001: A Space Odyssey (1968)'
 b'3 Ninjas: High Noon At Mega Mountain (1998)' b'39 Steps, The (1935)']

The total count of users:  943
The total count of movies:  1664


## Architecture of our model
The Goal is to give the

In [24]:
class MovielensModel(tfrs.models.Model):

  def __init__(self, rating_weight: float, retrieval_weight: float) -> None:
    # We take the loss weights in the constructor: this allows us to instantiate
    # several model objects with different loss weights.

    super().__init__()

    embedding_dimension = 32

    # User and movie models.
    self.movie_model: tf.keras.layers.Layer = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_movie_titles, mask_token=None),
      tf.keras.layers.Embedding(len(unique_movie_titles) + 1, embedding_dimension)
    ])
    self.user_model: tf.keras.layers.Layer = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_user_ids, mask_token=None),
      tf.keras.layers.Embedding(len(unique_user_ids) + 1, embedding_dimension)
    ])

    # A small model to take in user and movie embeddings and predict ratings.
    # We can make this as complicated as we want as long as we output a scalar
    # as our prediction.
    self.rating_model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dense(1),
    ])

    # The tasks.
    self.rating_task: tf.keras.layers.Layer = tfrs.tasks.Ranking(
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.RootMeanSquaredError()],
    )
    self.retrieval_task: tf.keras.layers.Layer = tfrs.tasks.Retrieval(
        metrics=tfrs.metrics.FactorizedTopK(
            candidates=movies.batch(128).map(self.movie_model)
        )
    )

    # The loss weights.
    self.rating_weight = rating_weight
    self.retrieval_weight = retrieval_weight

  def call(self, features: Dict[Text, tf.Tensor]) -> tf.Tensor:
    # We pick out the user features and pass them into the user model.
    user_embeddings = self.user_model(features["user_id"])
    # And pick out the movie features and pass them into the movie model.
    movie_embeddings = self.movie_model(features["movie_title"])

    return (user_embeddings, movie_embeddings,
        # We apply the multi-layered rating model to a concatentation of
        # user and movie embeddings.
        self.rating_model(
            tf.concat([user_embeddings, movie_embeddings], axis=1)
        ),
    )

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    ratings = features.pop("user_rating")
    user_embeddings, movie_embeddings, rating_predictions = self(features)

    # We compute the loss for each task.
    rating_loss = self.rating_task(
        labels=ratings,
        predictions=rating_predictions,
    )
    retrieval_loss = self.retrieval_task(user_embeddings, movie_embeddings)

    # And combine them using the loss weights.
    return (self.rating_weight * rating_loss
            + self.retrieval_weight * retrieval_loss)


## Building our model

In [25]:
model = MovielensModel(rating_weight=1.0, retrieval_weight=0.0)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

In [26]:
cached_train = train.shuffle(100_000).batch(8192).cache()
cached_test = test.batch(4096).cache()

In [27]:
history = model.fit(cached_train, epochs=3)
metrics = model.evaluate(cached_test, return_dict=True)

print(f"Retrieval top-100 accuracy: {metrics['factorized_top_k/top_100_categorical_accuracy']:.3f}.")
print(f"Ranking RMSE: {metrics['root_mean_squared_error']:.3f}.")

Epoch 1/3
10/10 [==============================] - 11s 942ms/step - root_mean_squared_error: 2.1329 - factorized_top_k/top_1_categorical_accuracy: 3.1250e-04 - factorized_top_k/top_5_categorical_accuracy: 0.0028 - factorized_top_k/top_10_categorical_accuracy: 0.0057 - factorized_top_k/top_50_categorical_accuracy: 0.0295 - factorized_top_k/top_100_categorical_accuracy: 0.0587 - loss: 4.1820 - regularization_loss: 0.0000e+00 - total_loss: 4.1820
Epoch 2/3
10/10 [==============================] - 10s 973ms/step - root_mean_squared_error: 1.1209 - factorized_top_k/top_1_categorical_accuracy: 2.3750e-04 - factorized_top_k/top_5_categorical_accuracy: 0.0028 - factorized_top_k/top_10_categorical_accuracy: 0.0057 - factorized_top_k/top_50_categorical_accuracy: 0.0296 - factorized_top_k/top_100_categorical_accuracy: 0.0588 - loss: 1.2561 - regularization_loss: 0.0000e+00 - total_loss: 1.2561
Epoch 3/3
5/5 [==============================] - 3s 318ms/step - root_mean_squared_error: 1.1069 - facto

In [28]:
def couple_movie_recommendation(model, user_id_1, user_id_2, unique_movie_titles):
    movie_recommendation_1 = 0
    movie_recommendation_2 = 0
    d = {'movie_title': unique_movie_titles, 'rating': np.zeros(len(unique_movie_titles))}
    movie_recommendation_couple = pd.DataFrame(data=d)
    for i in range(len(movie_recommendation_couple)):
        trained_movie_embeddings_1, trained_user_embeddings_1, predicted_rating_1 = model({"user_id": user_id_1, "movie_title": np.array([movie_recommendation_couple[i, 'movie_title']])})
        trained_movie_embeddings_2, trained_user_embeddings_2, predicted_rating_2 = model({"user_id": user_id_2, "movie_title": np.array([movie_recommendation_couple[i, 'movie_title']])})
        movie_recommendation_couple[i, 'rating'] = compute_combined_rating(predicted_rating_1, predicted_rating_2)

    movie_recommendation_couple = movie_recommendation_couple.sort_values(by='rating', ascending=False)

    for row in movie_recommendation_couple:
        print(row)


def compute_combined_rating(rating_1, rating_2):
    return (rating_1 + rating_2)/2


## Evaluating our model

In [29]:
trained_movie_embeddings, trained_user_embeddings, predicted_rating = model({
      "user_id": np.array(["42"]),
      "movie_title": np.array(["Dances with Wolves (1990)"])
  })
print("Predicted rating:")
print(predicted_rating)
print("trained_movie_embeddings:")
print(trained_movie_embeddings)
print("trained_user_embeddings:")
print(trained_user_embeddings)



Predicted rating:
tf.Tensor([[3.5135245]], shape=(1, 1), dtype=float32)
trained_movie_embeddings:
tf.Tensor(
[[-0.01431724 -0.02149155 -0.02784723  0.05116696 -0.0115958  -0.03359572
  -0.01087886  0.00607008 -0.02307403 -0.01878095  0.01820388  0.01833421
  -0.03660244  0.00123982 -0.03428502  0.03208422  0.03898733 -0.00036983
  -0.02397721 -0.024283   -0.024851   -0.00232851 -0.03945737 -0.0443373
   0.02509756  0.03524518  0.02676095 -0.01612241 -0.04987004  0.03569703
  -0.0197584  -0.01815905]], shape=(1, 32), dtype=float32)
trained_user_embeddings:
tf.Tensor(
[[ 0.03436362  0.02852535 -0.05066688  0.04563563  0.00107277 -0.02550413
  -0.01959895 -0.03277977 -0.04526854 -0.02615466 -0.00598134  0.0444752
   0.00992196  0.02416536 -0.01674729 -0.04047958 -0.0098563   0.01195646
  -0.04560608  0.01962575  0.0324471  -0.02734388 -0.01423968 -0.00744643
   0.00998831 -0.03699779 -0.04267216  0.00044611  0.01484042 -0.01689208
   0.01840374  0.04057774]], shape=(1, 32), dtype=float32)

In [ ]:
couple_movie_recommendation(model, 21, 13, unique_movie_titles)